services:
    web:
        build:
            context: ./web/cifrovic
        ports:
            - "3000:80"
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "8080:8080"
