name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          docker-compose-file: docker-compose.yaml
