name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development 

                    
      - name: Swagger UI Action
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: backend/swagger.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker-compose.yml  

      - name: Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
